version: "3.7"

services:
  database:
    image: postgres
    container_name: database-alpha
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vinicius
      - POSTGRES_PASSWORD=alpha
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres    
   
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/urs/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local